### ISSUE TITLE
Please add sentence-transformers and nlgeval to required packages in setup.py

### ISSUE THREAD

**Issue by avidale** [RussianNLP/russian_paraphrasers#1]
This will make the package work just after `pip install russian_paraphrasers`

**Comment by Alenush** [comment]
Yes, thank you! 

Have problems with pypi, cause it wan't install nlg-eval - it's not a direct dependency.

I add everything in setup. You can install directly with all packages like this:
```
pip install git+https://github.com/RussianNLP/russian_paraphrasers@master
```
